{
 "title": "Silence",
 "tags": [
  "silence",
  "scooter"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Energie",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"silence\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"scooter\")\n  |> filter(fn: (r) => r[\"imei\"] == \"860873040580135\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bsoc\" or r[\"_field\"] == \"range\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Location",
   "type": "geomap",
   "gridPos": { "h": 24, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "import \"experimental/geo\"\nfrom(bucket: \"silence\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"scooter\")\n  |> filter(fn: (r) => r[\"imei\"] == \"860873040580135\")\n  |> filter(fn: (r) => r[\"_field\"] == \"lat\" or r[\"_field\"] == \"lon\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> geo.toRows()"
    },
    {
     "query": "from(bucket: \"silence\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"scooter\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bsoc\")\n  |> filter(fn: (r) => r[\"imei\"] == \"860873040580135\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n  "
    }
   ]
  },
  {
   "title": "Temperaturen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"silence\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"scooter\")\n  |> filter(fn: (r) => r[\"imei\"] == \"860873040580135\")\n  |> filter(fn: (r) => r[\"_field\"] == \"btemp\" or r[\"_field\"] == \"itemp\" or r[\"_field\"] == \"mtemp\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Movement",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "from(bucket: \"silence\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"scooter\")\n  |> filter(fn: (r) => r[\"imei\"] == \"860873040580135\")\n  |> filter(fn: (r) => r[\"_field\"] == \"odo\" or r[\"_field\"] == \"speed\" or r[\"_field\"] == \"velocity\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}